version: '3.1'

services:
  user-service:
    build: .
    container_name: "user-service"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - network
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=user-service
  mongodb:
    image: 'mongo:latest'
    container_name: "mongodb"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - network
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

networks:
  network:
